// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwpPpV9S054jWQugvg8oTr7PT8HAFR2T8',
    appId: '1:869932405437:web:1c467c37ce3448181b9dd4',
    messagingSenderId: '869932405437',
    projectId: 'vacation-scheduling-ee49f',
    authDomain: 'vacation-scheduling-ee49f.firebaseapp.com',
    storageBucket: 'vacation-scheduling-ee49f.firebasestorage.app',
    measurementId: 'G-1H584GEX4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdyi2NpnmxvVY7Gz3ddvmx4X5wXu6-x9s',
    appId: '1:869932405437:android:ac4b87de8f1ee1001b9dd4',
    messagingSenderId: '869932405437',
    projectId: 'vacation-scheduling-ee49f',
    storageBucket: 'vacation-scheduling-ee49f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtn3j3oHLKa_TRhMlyL_0P2eIs_QB6Kxo',
    appId: '1:869932405437:ios:290ea4a8344968521b9dd4',
    messagingSenderId: '869932405437',
    projectId: 'vacation-scheduling-ee49f',
    storageBucket: 'vacation-scheduling-ee49f.firebasestorage.app',
    iosBundleId: 'com.silverithm.app.frontendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtn3j3oHLKa_TRhMlyL_0P2eIs_QB6Kxo',
    appId: '1:869932405437:ios:290ea4a8344968521b9dd4',
    messagingSenderId: '869932405437',
    projectId: 'vacation-scheduling-ee49f',
    storageBucket: 'vacation-scheduling-ee49f.firebasestorage.app',
    iosBundleId: 'com.silverithm.app.frontendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwpPpV9S054jWQugvg8oTr7PT8HAFR2T8',
    appId: '1:869932405437:web:a75b5983b7d0dea51b9dd4',
    messagingSenderId: '869932405437',
    projectId: 'vacation-scheduling-ee49f',
    authDomain: 'vacation-scheduling-ee49f.firebaseapp.com',
    storageBucket: 'vacation-scheduling-ee49f.firebasestorage.app',
    measurementId: 'G-2XGM627T8C',
  );
}
